language: c++

dist: trusty

cache:
    directories:
        - Qt

addons:
    apt:
        packages:
            - git
            - g++
            - make
            # a Qt dependency
            - mesa-common-dev

before_install:
    - if [ ! -e Qt/5.9.1 ] ; then
          rm -rf Qt ;
          wget http://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run ;
          chmod +x ./qt-opensource-linux-x64-5.9.1.run ;
          ./qt-opensource-linux-x64-5.9.1.run --platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
      fi
      # TestPreferences uses gui calls, so run a xvfb so it has something to talk to
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"


script:
    - export PATH=$PWD/Qt/5.9.1/gcc_64/bin:$PATH;
      mkdir ../build &&
      cd ../build
    - qmake -r ../qtquick-chart-travis
    - make
    - make check


